spring.application.name=first-try-or-tenth-be
spring.config.import=optional:file:.env[.properties]

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#toggle data.sql init, value: always/never
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true


spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}