spring.application.name=first-try-or-tenth-be
#Load env file vars
spring.config.import=optional:file:.env[.properties]
server.port=${PORT:8080}
#Data config
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
#toggle data.sql init script, value: always/never
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
#Logging
logging.level.org.springframework.security=DEBUG
#Custom app config
#24 hours
app.auth.jwt-expiration=86400000
app.cors.allowed-origins=${CORS_ORIGINS}
#Swagger
springdoc.swagger-ui.path=/api/v1/swagger-ui.html
springdoc.api-docs.path=/api/v1/api-docs
springdoc.default-produces-media-type:application/json
# Tells Spring to trust the X-Forwarded headers sent by Nginx
server.forward-headers-strategy=native
